9_wo_2_v0_gpt4_no_ex:
  batch_size: 1
  completion_parser_kwargs:
    matcher:
      A: 1.0
      B: 2.0
      tie: 0.0
  completions_kwargs:
    max_tokens: 100
    model_name: gpt-4
    temperature: 0
  fn_completion_parser: match_parser
  fn_completions: openai_completions
  prompt_template: templates_generated/9_wo_2_v0_gpt4_no_ex.txt
