gpt4_v5:
  prompt_template: "templates/gpt4_v5.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-4"
    max_tokens: 100
    temperature: 0
  fn_completion_parser: "match_parser"
  completion_parser_kwargs:
    matcher:
      A: 1.0
      B: 2.0
      tie: 0.0
  batch_size: 1
